from fastapi import FastAPI, HTTPException, File, UploadFile, Form
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware 
import os
import shutil
import customData

import User

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  
    allow_credentials=True,
    allow_methods=["*"],  
    allow_headers=["*"],  
)

class UserRequest(BaseModel):
    email: str
    password: str

@app.get("/")
def read_root():
    return {"message": "Welcome to the PBL-1 API"}

@app.post("/signup")
def signup_endpoint(user: UserRequest):
    result = User.signUp(user.email, user.password)
    if result["status"] == "error":
        raise HTTPException(status_code=400, detail=result["message"])
    return result

@app.post("/login")
def login_endpoint(user: UserRequest):
    result = User.logIn(user.email, user.password)
    if result["status"] == "error":
        raise HTTPException(status_code=401, detail=result["message"])
    return result

@app.post("/upload-custom-dataset")
async def upload_dataset(
    file: UploadFile = File(...), 
    email: str = Form(...)
):
    if not file.filename.endswith(".xlsx"):
        raise HTTPException(status_code=400, detail="Only .xlsx files are accepted")
    
    # Ignore temporary/lock files generated by MS Excel/LibreOffice
    if file.filename.startswith(".~lock") or file.filename.startswith("~$"):
        raise HTTPException(status_code=400, detail="Please close the Excel file before uploading. Temporary lock files are not supported.")

    os.makedirs("DataSets/CustomDataSet", exist_ok=True)
    os.makedirs("Graphs/CustomGraphs", exist_ok=True)
    
    safe_email = email.replace("@", "_").replace(".", "_")
    file_location = f"DataSets/CustomDataSet/{safe_email}_dataset.xlsx"
    
    # Debug: Confirm directory exists and path is correct
    print(f"DEBUG: Saving to {os.path.abspath(file_location)}")
    
    with open(file_location, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
    
    # Check if file was actually written
    if not os.path.exists(file_location):
        print("DEBUG: File failed to save!")
        raise HTTPException(status_code=500, detail="Failed to save uploaded file")

    try:
        # Debug: Check process call
        print(f"DEBUG: Processing file {file_location} for {safe_email}")
        countries = customData.process_custom_dataset(file_location, safe_email)
        print(f"DEBUG: Processed successfully. Countries found: {countries}")
        return {
            "message": "File processed and graphs generated",
            "countries": countries,
            "emailPrefix": safe_email
        }
    except Exception as e:
        import traceback
        traceback.print_exc()
        if os.path.exists(file_location):
            os.remove(file_location)
        raise HTTPException(status_code=500, detail=str(e))
